In [1]:
import numpy as np

print(np.__version__)

2.4.1


In [3]:
arr2 = np.array([[1, 2, 3], 
                 [4, 5, 6],
                [10,11,12]])
print(arr2)
print(arr2.shape)
print(arr2.ndim)


[[ 1  2  3]
 [ 4  5  6]
 [10 11 12]]
(3, 3)
2


In [ ]:
print(arr2[1, 2])  # Accessing element at row 1, column 2

In [4]:
import pandas as pd

KeyboardInterrupt: 

In [3]:
pip install pandas

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.3 -> 26.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import pandas as pd
data = {'Name': ['Alice', 'Bob', 'Charlie'],
        'Age': [25, 30, 35],
        'City': ['New York', 'Los Angeles', 'Chicago']}
df = pd.DataFrame(data)
df

Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago

In [1]:
pip install --upgrade pip

   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/1.8 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/1.8 MB ? eta -:--:--
   ----------- ---------------------------- 0.5/1.8 MB 823.6 kB/s eta 0:00:02
   ----------------- ---------------------- 0.8/1.8 MB 881.4 kB/s eta 0:00:02
   ----------------------- ---------------- 1.0/1.8 MB 924.3 kB/s eta 0:00:01
   ----------------------- ---------------- 1.0/1.8 MB 924.3 kB/s eta 0:00:01
   ----------------------------- ---------- 1.3/1.8 MB 873.8 kB/s eta 0:00:01
   ----------------------------------- ---- 1.6/1.8 MB 912.5 kB/s eta 0:00:01
   ---------------------------------------- 1.8/1.8 MB 958.8 kB/s  0:00:02
  Attempting uninstall: pip
    Found existing installation: pip 25.3
    Uninstalling pip-25.3:
      Successfu

  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.


In [ ]:
arr= np.array([[1, 2],
               [3, 4]])
arr=arr+5
print(arr)